services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/opt/app-root/src
    command: >
      sh -c "gunicorn --reload --bind 0.0.0.0:${PORT:-8080} --workers 1 wsgi:app"
